# Generated by Django 5.1.5 on 2025-06-18 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topuporder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topupproduct',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='topupproduct',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topuporder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topuporder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topup.topupproduct'),
        ),
        migrations.AlterField(
            model_name='topuporder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='topuporder',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='topupproduct',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topup.game'),
        ),
        migrations.AlterField(
            model_name='topupproduct',
            name='in_game_currency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topupproduct',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topupproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
